### ISSUE TITLE
Preview / Custom zoom levels

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#118]
Not so much an issue, however, it would be nice if the various buttons on this window had descriptions like the very helpful descriptions on the config window. 
At this point what is the difference between Save zone and apply? Are the little zoom level squares a zone or is the entire preview the zone?
Thank you.

**Comment by Hesynergy** [comment]
> Not so much an issue, however, it would be nice if the various buttons on this window had descriptions like the very helpful descriptions on the config window. At this point what is the difference between Save zone and apply? Are the little zoom level squares a zone or is the entire preview the zone? Thank you.

Im With you!! I cannot thank "Oscar" enough for his incredible Ortho4XP...which I used to create a modest 1.7TB in my Tiles folder.  That being said, Ive gone back to XP temporarily because MSFS and I are having a difference of opinion...I want it to run and it doesn't.  Soooooo sir"Botes of the Boats', Ive been trying to recapture the magic of XP via O4XP...and I heartily agree re the info tags missing from the CZL screen.  
Also, I thought I knew my shit having created all that Ortho scenery, but having the foresight to backup my last version of everything XP ...and having just FOUND it again....None of my tiles when referenced show the custom zoom levels they had(and still have according to their ZOrtho_036-84 tile from '17 .cfg file...what am I doing wrong ?...is the config file different in 1.30 from the version of O4XP back then?...what can I do to resurect that tile( and all other archived Zortho_TileLon_Tile00lat files with a .cfg attached, like 36-084 below.
++++++++++++++++++++++++++++++++++++++ 
# Tile specific config file : lat=36, lon=-84
default_website='BI'
default_zl=17
water_option=3
sea_texture_params=[]
cover_airports_with_highres=True
cover_zl=19
cover_extent=5
min_area=0.01
sea_equiv=['Étang de Berre', 'Estuaire de la Gironde', 'Lac Léman']
do_not_flatten_these_list=[]
meshzl=19
insert_custom_zoom_in_mesh=False
poly_simplification_tol=0.002
overpass_server_list={'1': 'http://api.openstreetmap.fr/oapi/interpreter', '3': 'http://overpass.osm.rambler.ru/cgi/interpreter', '2': 'http://overpass-api.de/api/interpreter'}
overpass_server_choice='2'
curvature_tol=3.0
no_small_angles=False
smallest_angle=5
hmin=20
hmax=2000
tile_has_water_airport=False
water_smoothing=2
sea_smoothing=0
masks_width=8
complex_masks=False
use_masks_for_inland=False
legacy_masks=True
keep_old_pre_mask=False
maskszl=14
use_gimp=False
gimp_cmd='J:\Program Files\GIMP 2in\gimp-console-2.8.exe'
ratio_water=0.3
normal_map_strength=0.3
terrain_casts_shadows=False
use_decal_on_terrain=False
dds_or_png='dds'
use_bing_for_non_existent_data=False
max_convert_slots=4
be_nice_timer=0
skip_downloads=False
skip_converts=False
check_tms_response=True
verbose_output=True
clean_tmp_files=True
clean_unused_dds_and_ter_files=True
contrast_adjust={}
brightness_adjust={}
saturation_adjust={}
full_color_correction={}
g2xpl_8_prefix='g2xpl_8_'
g2xpl_8_suffix=''
g2xpl_16_prefix='g2xpl_16_'
g2xpl_16_suffix=''
Custom_scenery_prefix=''
Custom_scenery_dir=''
default_sniff_dir='K:/XP11 Testbed/X-Plane 11/Global Scenery/X-Plane 11 Global Scenery'
keep_orig_zuv=True
seven_zip=True
landclass_mesh_division=8
snap_to_z_grid=True
overlay_lod=40000
keep_overlays=True
zone_list=[]
zone_list.append([[36.87687432322355, -83.90499114990234, 36.877423587484586, -83.90190124511719, 36.87865941762908, -83.8996696472168, 36.879757916524596, -83.89623641967773, 36.880856399619006, -83.88971328735352, 36.88071909009632, -83.88404846191406, 36.88250409463318, -83.88490676879883, 36.884426360547366, -83.88799667358398, 36.89170307169378, -83.89348983764648, 36.893487819443564, -83.89074325561523, 36.89005557519408, -83.88404846191406, 36.885936678387836, -83.88336181640625, 36.88648587746806, -83.87958526611328, 36.883877146652765, -83.87529373168945, 36.88071909009632, -83.87392044067383, 36.87728627178964, -83.87083053588867, 36.874539906045385, -83.87100219726562, 36.87618773734232, -83.87752532958984, 36.87220541751914, -83.8754653930664, 36.86932153907276, -83.87666702270508, 36.865476198461394, -83.87786865234375, 36.86327877407527, -83.8747787475586, 36.86190535174326, -83.87289047241211, 36.86684955661147, -83.87151718139648, 36.8689095475503, -83.8641357421875, 36.865064186202645, -83.8615608215332, 36.8682228900756, -83.85932922363281, 36.870008186672834, -83.85675430297852, 36.874539906045385, -83.86310577392578, 36.878934043834306, -83.86499404907227, 36.880032538779545, -83.86035919189453, 36.88373984256185, -83.86104583740234, 36.8848382683758, -83.85692596435547, 36.88154294352894, -83.8502311706543, 36.8783847904363, -83.85126113891602, 36.875775782850994, -83.85040283203125, 36.87824747646957, -83.84782791137695, 36.880169849536685, -83.84714126586914, 36.880307160046954, -83.8425064086914, 36.87591310126166, -83.83718490600586, 36.87275471535585, -83.836669921875, 36.8783847904363, -83.82946014404297, 36.873441332097045, -83.82396697998047, 36.86932153907276, -83.82705688476562, 36.86643755175845, -83.83031845092773, 36.865064186202645, -83.836669921875, 36.862592065994875, -83.83804321289062, 36.857510234401104, -83.83186340332031, 36.8533895823349, -83.83220672607422, 36.852290704266, -83.83838653564453, 36.85091708446579, -83.84456634521484, 36.845010238078274, -83.84147644042969, 36.84377386363927, -83.84679794311523, 36.84459811548649, -83.85520935058594, 36.843224357471755, -83.86310577392578, 36.840202002966066, -83.86482238769531, 36.845422358448786, -83.87374877929688, 36.85682347448375, -83.88267517089844, 36.85792228738947, -83.88010025024414, 36.86231738103477, -83.88404846191406, 36.857510234401104, -83.88748168945312, 36.85668612175978, -83.89108657836914, 36.858334338156325, -83.8970947265625, 36.85668612175978, -83.90035629272461, 36.85792228738947, -83.90602111816406, 36.86698689106876, -83.90859603881836, 36.8689095475503, -83.91151428222656, 36.86918420881214, -83.9187240600586, 36.87687432322355, -83.90499114990234], 19, 'BI'])
zone_list.append([[36.87110680999585, -83.7374496459961, 36.870008186672834, -83.73315811157227, 36.87151878966861, -83.73075485229492, 36.87151878966861, -83.726806640625, 36.875775782850994, -83.72354507446289, 36.877698218133816, -83.72594833374023, 36.877835533088074, -83.7293815612793, 36.87687432322355, -83.7319564819336, 36.877423587484586, -83.73470306396484, 36.87865941762908, -83.73607635498047, 36.879345981290456, -83.73796463012695, 36.88126832670564, -83.74345779418945, 36.88154294352894, -83.74740600585938, 36.87920866905196, -83.74774932861328, 36.875089187094446, -83.74500274658203, 36.873853299179245, -83.74809265136719, 36.87110680999585, -83.7491226196289, 36.86698689106876, -83.74946594238281, 36.86465217172221, -83.75118255615234, 36.8695961988534, -83.75616073608398, 36.86781089262841, -83.7594223022461, 36.86190535174326, -83.7542724609375, 36.85737288291131, -83.75289916992188, 36.857235531174666, -83.74946594238281, 36.85957047712755, -83.74534606933594, 36.86781089262841, -83.74156951904297, 36.8695961988534, -83.73693466186523, 36.869046878304644, -83.73418807983398, 36.87110680999585, -83.7374496459961], 19, 'BI'])
zone_list.append([[36.77367999013593, -83.71788024902344, 36.77271747099006, -83.71599197387695, 36.772442463300195, -83.71341705322266, 36.77202994991576, -83.71084213256836, 36.768592252062675, -83.70414733886719, 36.769142294076985, -83.6967658996582, 36.766942102345155, -83.69213104248047, 36.770654889270716, -83.68698120117188, 36.77381749188457, -83.67668151855469, 36.77601748632149, -83.66706848144531, 36.77436749641282, -83.6469841003418, 36.76336665613411, -83.64217758178711, 36.76432929266687, -83.6667251586914, 36.76281657269024, -83.67788314819336, 36.75924093413333, -83.6854362487793, 36.75621526361752, -83.69298934936523, 36.75401470100921, -83.69813919067383, 36.75415223802155, -83.70431900024414, 36.7534645504941, -83.71135711669922, 36.751814075277906, -83.7209701538086, 36.76281657269024, -83.7238883972168, 36.759653516320355, -83.72749328613281, 36.76075372463585, -83.73418807983398, 36.766254529482026, -83.73556137084961, 36.771892444961026, -83.73470306396484, 36.7749174969951, -83.73504638671875, 36.77367999013593, -83.71788024902344], 19, 'BI'])
zone_list.append([[36.60670888641815, -83.75478744506836, 36.60092103702007, -83.7652587890625, 36.601885708744234, -83.77521514892578, 36.602574752590314, -83.78345489501953, 36.61442534338386, -83.7843132019043, 36.62599858106557, -83.77744674682617, 36.62765175890193, -83.76457214355469, 36.62999370013604, -83.75101089477539, 36.635228370260634, -83.74225616455078, 36.64390611879395, -83.74174118041992, 36.64886439335538, -83.74122619628906, 36.64707394214096, -83.73384475708008, 36.641702338752765, -83.73212814331055, 36.64376838438855, -83.72852325439453, 36.645421180998056, -83.72182846069336, 36.63922301084294, -83.71736526489258, 36.642253289673974, -83.7132453918457, 36.642253289673974, -83.70878219604492, 36.64142686181442, -83.70552062988281, 36.64707394214096, -83.70088577270508, 36.63880978176677, -83.69865417480469, 36.6327488340026, -83.69762420654297, 36.62613634723962, -83.69504928588867, 36.62448313689886, -83.6880111694336, 36.61883440069683, -83.69556427001953, 36.6134608284878, -83.69281768798828, 36.61029162317227, -83.68972778320312, 36.60753568659493, -83.682861328125, 36.602574752590314, -83.67925643920898, 36.60133446923608, -83.6883544921875, 36.598716027782075, -83.6909294128418, 36.59416799719804, -83.70157241821289, 36.586725187102246, -83.71822357177734, 36.58341704111031, -83.73453140258789, 36.60670888641815, -83.75478744506836], 19, 'BI'])
zone_list.append([[36.58451977219386, -83.66621017456055, 36.593341053744936, -83.65470886230469, 36.59954291363164, -83.64080429077148, 36.593616702547294, -83.62174987792969, 36.58507113182833, -83.6140251159668, 36.57335389229773, -83.62295150756836, 36.55873931401891, -83.62329483032227, 36.55363734795711, -83.63874435424805, 36.54798342455153, -83.64578247070312, 36.542880748389024, -83.65213394165039, 36.55405103343023, -83.6667251586914, 36.57183741370244, -83.67170333862305, 36.58451977219386, -83.66621017456055], 19, 'BI'])
zone_list.append([[36.40815885862307, -83.56733322143555, 36.40995484857842, -83.56063842773438, 36.41382299361494, -83.55188369750977, 36.41465185677697, -83.54690551757812, 36.41147449995712, -83.54330062866211, 36.40705361339839, -83.5426139831543, 36.402908803774466, -83.54621887207031, 36.39904011531523, -83.5513687133789, 36.39586212000637, -83.56029510498047, 36.392545812446244, -83.56681823730469, 36.39378944436183, -83.57145309448242, 36.398072913107896, -83.57608795166016, 36.40332329468629, -83.57625961303711, 36.40884962890405, -83.57625961303711, 36.40995484857842, -83.57093811035156, 36.40815885862307, -83.56733322143555], 19, 'BI'])
zone_list.append([[36.4175528081898, -83.64166259765625, 36.417967220975086, -83.6337661743164, 36.421558705817304, -83.6198616027832, 36.42487377516866, -83.60235214233398, 36.43012234551577, -83.58861923217773, 36.43067480596372, -83.57316970825195, 36.431365375994616, -83.56012344360352, 36.44324221892113, -83.55274200439453, 36.45912120326335, -83.55669021606445, 36.46229661004962, -83.56647491455078, 36.45290807477076, -83.594970703125, 36.443794585983625, -83.60733032226562, 36.43813263718111, -83.6305046081543, 36.4338513772381, -83.63788604736328, 36.422111227204425, -83.64715576171875, 36.4175528081898, -83.64166259765625], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.83786646539974, -83.37799072265625, 36.840064620377674, -83.34365844726562, 36.852153343396665, -83.30795288085938, 36.877423587484586, -83.33404541015625, 36.87522650673951, -83.39309692382812, 36.83786646539974, -83.37799072265625], 19, 'BI'])
zone_list.append([[36.66180949419196, -83.2708740234375, 36.66731738757093, -83.19534301757812, 36.6574028957064, -83.19259643554688, 36.63536611993544, -83.19808959960938, 36.64638529597498, -83.25164794921875, 36.66180949419196, -83.2708740234375], 19, 'BI'])
zone_list.append([[36.49086941889726, -83.29559326171875, 36.48976535146369, -83.23928833007812, 36.522880528051374, -83.21182250976562, 36.51956964788293, -83.2598876953125, 36.510739941466724, -83.30245971679688, 36.49086941889726, -83.29559326171875], 19, 'BI'])
zone_list.append([[36.417967220975086, -83.11981201171875, 36.442275567099685, -83.14041137695312, 36.47761957109452, -83.133544921875, 36.47209813242351, -83.0950927734375, 36.46547188679814, -83.056640625, 36.417967220975086, -83.11981201171875], 19, 'BI'])
zone_list.append([[36.307378846789774, -83.78036499023438, 36.34389038251925, -83.83941650390625, 36.38259604087706, -83.81332397460938, 36.37706783983681, -83.76251220703125, 36.32176422120382, -83.75015258789062, 36.307378846789774, -83.78036499023438], 19, 'BI'])
zone_list.append([[36.17335693522159, -83.44802856445312, 36.21879505532196, -83.38760375976562, 36.24095042144499, -83.31069946289062, 36.24095042144499, -83.22967529296875, 36.19774164407363, -83.22555541992188, 36.14452885702774, -83.38211059570312, 36.124564748133295, -83.4466552734375, 36.17335693522159, -83.44802856445312], 19, 'BI'])
zone_list.append([[36.13898378070337, -83.75289916992188, 36.15672664526235, -83.71307373046875, 36.20439070158872, -83.75564575195312, 36.16559657231973, -83.77899169921875, 36.13898378070337, -83.75289916992188], 19, 'BI'])
zone_list.append([[36.16892253622743, -83.63616943359375, 36.17335693522159, -83.5784912109375, 36.13898378070337, -83.572998046875, 36.124564748133295, -83.61968994140625, 36.16892253622743, -83.63616943359375], 19, 'BI'])
zone_list.append([[36.125673998536044, -83.13766479492188, 36.14341987311765, -83.11431884765625, 36.14120185826492, -83.07174682617188, 36.12678323326426, -83.06625366210938, 36.100157274022266, -83.07998657226562, 36.09571873655538, -83.11431884765625, 36.125673998536044, -83.13766479492188], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'GO2'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'GO2'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'GO2'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'GO2'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], 19, 'BI'])
zone_list.append([[36.870008186672834, -83.91374588012695, 36.86602554468374, -83.92507553100586, 36.85915843302537, -83.92473220825195, 36.8535269409828, -83.92112731933594, 36.84377386363927, -83.91992568969727, 36.840064620377674, -83.90722274780273, 36.84363648746759, -83.89366149902344, 36.841301054788715, -83.8861083984375, 36.834156935615496, -83.87666702270508, 36.83017242546417, -83.86585235595703, 36.83264559412652, -83.85160446166992, 36.823714330358214, -83.84765625, 36.82687474287728, -83.82843017578125, 36.831546417925196, -83.8176155090332, 36.83113422277796, -83.81452560424805, 36.81890475650876, -83.79581451416016, 36.81354516103298, -83.78620147705078, 36.80722310453565, -83.77298355102539, 36.81299543771418, -83.7568473815918, 36.821103456345156, -83.75410079956055, 36.82165312143451, -83.74105453491211, 36.82082862231999, -83.7264633178711, 36.82563807526324, -83.72011184692383, 36.832370801556834, -83.70895385742188, 36.83649258645616, -83.70500564575195, 36.84377386363927, -83.7019157409668, 36.8570981791912, -83.69436264038086, 36.86863488530102, -83.69762420654297, 36.88222948126645, -83.70311737060547, 36.89513524186593, -83.70277404785156, 36.90145003174085, -83.69865417480469, 36.90199911920969, -83.68852615356445, 36.90474449728603, -83.68268966674805, 36.90735251496183, -83.67908477783203, 36.91160751029993, -83.67650985717773, 36.91929335186059, -83.67513656616211, 36.92560614227527, -83.6886978149414, 36.93479992369487, -83.69985580444336, 36.93658366327918, -83.71753692626953, 36.930271781871554, -83.74414443969727, 36.92464553397127, -83.74534606933594, 36.91874438886404, -83.74517440795898, 36.91750920767299, -83.75547409057617, 36.91421529335739, -83.75925064086914, 36.910372213522535, -83.76216888427734, 36.90529356104756, -83.7649154663086, 36.89911636591847, -83.77246856689453, 36.889918282214126, -83.7872314453125, 36.88511287236025, -83.79100799560547, 36.88428905744405, -83.81315231323242, 36.88236678807324, -83.82207870483398, 36.88332792880773, -83.8282585144043, 36.89019286792713, -83.83718490600586, 36.893487819443564, -83.84078979492188, 36.89458610500934, -83.85229110717773, 36.89403696420189, -83.86070251464844, 36.89801814554322, -83.86430740356445, 36.905156295477624, -83.85967254638672, 36.90735251496183, -83.86070251464844, 36.906117149281144, -83.86791229248047, 36.90282274300452, -83.87718200683594, 36.90543082637056, -83.88336181640625, 36.90501902966071, -83.8916015625, 36.904195429573235, -83.89984130859375, 36.870008186672834, -83.91374588012695], 18, 'BI'])
zone_list.append([[36.8084600697111, -83.76903533935547, 36.8021375933119, -83.76285552978516, 36.796639363428284, -83.76337051391602, 36.7892161270094, -83.76285552978516, 36.78426690313161, -83.7539291381836, 36.78440438588913, -83.7458610534668, 36.77670497163503, -83.74465942382812, 36.77161743431175, -83.73590469360352, 36.7762924811868, -83.72526168823242, 36.78096724295662, -83.72200012207031, 36.78715398924224, -83.71702194213867, 36.795539670087805, -83.72045516967773, 36.79306530234898, -83.7297248840332, 36.802962293750866, -83.7322998046875, 36.812308278014385, -83.73161315917969, 36.8092847020594, -83.72629165649414, 36.812033412407416, -83.72320175170898, 36.818217649856024, -83.72354507446289, 36.82288985345096, -83.72440338134766, 36.82343950570947, -83.75375747680664, 36.8084600697111, -83.76903533935547], 18, 'BI'])
zone_list.append([[36.644457053952635, -83.75736236572266, 36.64748712688497, -83.75616073608398, 36.65340919795271, -83.75873565673828, 36.65905539969829, -83.74740600585938, 36.65754060572718, -83.71942520141602, 36.65547492955113, -83.70294570922852, 36.64032494420971, -83.68698120117188, 36.6246209057816, -83.67427825927734, 36.60629548300612, -83.66878509521484, 36.59237627518267, -83.66861343383789, 36.580522297068384, -83.68131637573242, 36.57280244898129, -83.70140075683594, 36.56425457405503, -83.7322998046875, 36.55763621476535, -83.74895095825195, 36.55639520928092, -83.75701904296875, 36.55212048227604, -83.76972198486328, 36.55556786121835, -83.7759017944336, 36.56177275576226, -83.78620147705078, 36.558325653644346, -83.79358291625977, 36.552809970367335, -83.80319595336914, 36.54936246839779, -83.82225036621094, 36.55529207656234, -83.8231086730957, 36.56646056782459, -83.8117790222168, 36.58176291494888, -83.80010604858398, 36.58341704111031, -83.79323959350586, 36.58465761247169, -83.78602981567383, 36.59127365634204, -83.78019332885742, 36.59885384270575, -83.78808975219727, 36.59720004737392, -83.80182266235352, 36.590584511566576, -83.8088607788086, 36.590171021747466, -83.81795883178711, 36.59292757869521, -83.82379531860352, 36.60092103702007, -83.82877349853516, 36.61153176250255, -83.83769989013672, 36.621038834802874, -83.8260269165039, 36.63426411564153, -83.84542465209961, 36.65230745177237, -83.8418197631836, 36.65933081358165, -83.82413864135742, 36.63936075337574, -83.79135131835938, 36.644457053952635, -83.75736236572266], 18, 'BI'])
zone_list.append([[36.44807529738651, -83.50038528442383, 36.43523245463615, -83.51068496704102, 36.42680750026264, -83.5184097290039, 36.42003925173172, -83.53660583496094, 36.41520442730446, -83.5536003112793, 36.410921902895325, -83.56544494628906, 36.41175079701392, -83.5814094543457, 36.40318513129466, -83.59085083007812, 36.38909117495406, -83.6085319519043, 36.3759621524743, -83.62123489379883, 36.375823940448825, -83.63737106323242, 36.366010258936925, -83.63428115844727, 36.368913026057015, -83.60715866088867, 36.38066121521226, -83.56407165527344, 36.395309411905245, -83.53986740112305, 36.405948352450736, -83.52012634277344, 36.417829083625676, -83.50553512573242, 36.42680750026264, -83.49437713623047, 36.431227262479894, -83.48871231079102, 36.44807529738651, -83.50038528442383], 18, 'BI'])
zone_list.append([[36.359374956015856, -83.6279296875, 36.359374956015856, -83.485107421875, 36.46547188679814, -83.485107421875, 36.46547188679814, -83.6279296875, 36.359374956015856, -83.6279296875], '19', 'BI'])

Thanks for your kind attention
Sending all who see this and your loved ones protective and healing vibes
Chas

**Comment by oscarpilote** [comment]
Will think about it. I agree this can look cryptic. Maybe the youtube tutorial that I once made did explain that.
