### ISSUE TITLE
Uncaught OSM error

### ISSUE THREAD

**Issue by fagidutt** [oscarpilote/Ortho4XP#161]
Hello there, i got this error:

`ERROR: Triangle4XP really couldn't make it !

If the reason is not due to the limited amount of RAM please
file a bug including the .node and .poly files that you
will find in .\Tiles\zOrtho4XP_+57-007.`

Those are the respective .node and .poly files. Is anyone here able to help me with it?

Thanks a lot!
[zOrtho4XP_+57-007.zip](https://github.com/oscarpilote/Ortho4XP/files/6910990/zOrtho4XP_%2B57-007.zip)

**Comment by d41k4n** [comment]
I'm unable to reproduce based on the provided information (which is missing the complete config for example).
See [here](https://forums.x-plane.org/index.php?/forums/topic/250086-uncaught-osm-error/&do=findComment&comment=2228111) for further troubleshooting instructions.

**Comment by d41k4n** [comment]
This is an issue caused by invalid/ecroached road geometry in OSM which Ortho4XP couldn't clean up. It's not really a bug but rather a limitation of the input data.
The easiest workaround is reducing road_level (in my case it worked with a value of 3).  BEst would be fixing the bad road segments in OSM but that is out if scope here.
