### ISSUE TITLE
Progress Bars are not much good as they are now. 

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#168]
The progress bars do not reflect actual progress in many steps. 
Why are there three bars in the first place?
They fill up, then jump back and forth, not actually indicating much of anything. Hovering a pointer or clicking on them returns no information. 
The scrolling text is more useful in many cases.
Why not eliminate or change the bars to convey useful accurate information.

**Comment by oscarpilote** [comment]
I believe they convey useful accurate information. They don't give you a "remaining time", because not all tasks have predictable duration. The the granularity is not the full Step but intermediate jobs (as announced in the console), because it helps (developers at least) to catch the performance bottlenecks. There are three of them because they monitor different things (e.g. for Step 3 the left most is DSF creation, the middle one is image download, and the right most is image dds conversion).
