### ISSUE TITLE
Plans to use PyOpenCL to improve performance?

### ISSUE THREAD

**Issue by kbrandwijk** [oscarpilote/Ortho4XP#20]
Especially in the first step and the tile conversion, using the GPU would drastically improve performance. I'm looking into this, but I'd like to know if you have any plans to include this already?

**Comment by oscarpilote** [comment]
No plan on my side. Step 1 is mainly bound to C GEOS I would say and I am not sure there is a lot to win there since we are already combining it with a spatial index for minimizing the geometry computations. DDS conversion can go through the GPU if you nvcompress version has it (although according to what I have seen it doesn't make such a noticeable difference).
