### ISSUE TITLE
Default source

### ISSUE THREAD

**Issue by chevdor** [oscarpilote/Ortho4XP#206]
Is it possible to setup a default source, especially for the Zoom Level editor ?
It seems that the default is OSM, is there a reason for that ?

**Comment by d41k4n** [comment]
The default source is the one last selected in the main window. FYI: Whenever Ortho4XP shuts down normally the main window parameters are saved in file `.last_gui_params.txt`. This file is then read at the next start in order to populate the source parameters in the main and zoom level windows (under "Zone params"). 

However, the pre-selected source for the preview function is [currently hardcoded to `OSM`](https://github.com/oscarpilote/Ortho4XP/blob/7ed9a092541bc3bcee810c59f07d12f885f97f17/src/O4_GUI_Utils.py#L408)). The reason for that is because the OSM layer includes administrative boundaries and names which are typically useful for identifying locations and POI's.

Btw, the official support forum is located [here](https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/). I recommend posting usage questions there rather than raising issues here.

**Comment by chevdor** [comment]
Hello @d41k4n,
thanks for your detailled answer.

> The default source is the one last selected in the main window.
If tihs is the supposed behavior, it does not work.
Thanks to your pointer to `.last_gui_params.txt`, I could edit the file and switch the default.

> However, the pre-selected source for the preview function is [currently hardcoded to OSM](https://github.com/oscarpilote/Ortho4XP/blob/7ed9a092541bc3bcee810c59f07d12f885f97f17/src/O4_GUI_Utils.py#L408)). The reason...
Ok clear, the issue is that OSM does not load (white content even when using a VPN) and crashes the App for me from time to time.

Thanks for the forum link, I am checking for a solution in there.

**Comment by chevdor** [comment]
btw OSM is returning an HTTP status 418 no matter what when using Ortho4XP so switching the default provider may help.
With your hint above, I can easily fix it myself but I think that all users trying will not help with the situation.
