### ISSUE TITLE
No more 'load poly' in v130?

### ISSUE THREAD

**Issue by kbrandwijk** [oscarpilote/Ortho4XP#21]
I tried out v130, but I'm missing the option to load a poly when defining sources for tiles. I can still draw a poly manually, but I can't load the standard country border polylines anymore.

**Comment by oscarpilote** [comment]
The feature is replaced by the more powerful notion of "combined providers". A combined provider is list of imagery layers each with its extent (a georeferenced png mask), color filters and priority. The extent replaces the poly, and by choosing appropriately the blur of the extent mask imageries get merged together rather than croped at triangle boundaries. You can probably already guess how it works in the example .comb file but I understand I should make a tutorial.

**Comment by kbrandwijk** [comment]
I completely missed that part, it sounds great though. I will look into it, and see if it makes sense.
