### ISSUE TITLE
Linux convert

### ISSUE THREAD

**Issue by akhenakh** [oscarpilote/Ortho4XP#25]
On Linux, no nvcompress binary is provided, so the convert process will fail.
But Imagemagick `convert` is capable of doing the job with GPU acceleration via OpenCL.

Since most Linux distributions can provide Imagemagick it would a reliable solution.
This is the patching I have to do on every releases :)
```
--- a/src/O4_Imagery_Utils.py
+++ b/src/O4_Imagery_Utils.py
@@ -49,7 +49,7 @@ elif 'win' in sys.platform:
     gdalwarp_cmd    = "gdalwarp.exe"
     devnull_rdir    = " > nul  2>&1"
 else:
-    dds_convert_cmd = "nvcompress" 
+    dds_convert_cmd = "convert" 
     gdal_transl_cmd = "gdal_translate"
     gdalwarp_cmd    = "gdalwarp"
     devnull_rdir    = " >/dev/null 2>&1 "
@@ -1285,7 +1285,8 @@ def convert_texture(tile,til_x_left,til_y_top,zoomlevel,provider_code,type='dds'
         file_to_convert=os.path.join(file_dir,jpeg_file_name)
     # eventually the dds conversion
     if type=='dds':
-        conv_cmd=[dds_convert_cmd,'-bc1','-fast',file_to_convert,os.path.join(tile.build_dir,'textures',out_file_name),devnull_rdir]
+        conv_cmd=[dds_convert_cmd,file_to_convert,os.path.join(tile.build_dir,'textures',out_file_name)]
     else:
         (latmax,lonmin)=GEO.gtile_to_wgs84(til_x_left,til_y_top,zoomlevel)
         (latmin,lonmax)=GEO.gtile_to_wgs84(til_x_left+16,til_y_top+16,zoomlevel)
```
A custom command without the nvcompress params would do the trick

**Comment by oscarpilote** [comment]
I'd recommend you instead to use nvcompress from your linux distribution (libnvtt-bin on debian based distros) rather than Imagemagick convert: the dds converted by the latter have slight artifacts in X-Plane (you'll notice them in water areas of almost uniform color, Imagemagick's convert was the default converter at the start of Ortho4XP but was discarded for that reason).

**Comment by Artur96** [comment]
`nvidia-texture-tools-git` on AUR provides `nvcompress`

**Comment by akhenakh** [comment]
@Artur96 I've finally built it myself, better use the Arch pkg thanks ;)

**Comment by Gfurst** [comment]
This should be given a little bit more attention, I had to dig in deep to figure out why the texture weren't getting converted despite the log throwing no error of the like, before finally finding this. Not only is nvcompress readily available on Arch (and I'd imagine other distributions as well), even after building my package of 'nvidia-texture-tools' through AUR, the tool would fail to convert for reasons unknown.
After applying the diffs above (with some adjustments since the source isn't the same anymore), I was finally able to convert those texture, I can't tell a far as performance, but haven't found any artifacts yet, it would be good to know what to look for. But given its been quite a long time since imagemagick has been cast out, we can hope that the issues have been fixed upstream.

**Comment by CabrioletDiskette** [comment]
> This should be given a little bit more attention, I had to dig in deep to figure out why the texture weren't getting converted despite the log throwing no error of the like, before finally finding this. Not only is nvcompress readily available on Arch (and I'd imagine other distributions as well), even after building my package of 'nvidia-texture-tools' through AUR, the tool would fail to convert for reasons unknown.
> After applying the diffs above (with some adjustments since the source isn't the same anymore), I was finally able to convert those texture, I can't tell a far as performance, but haven't found any artifacts yet, it would be good to know what to look for. But given its been quite a long time since imagemagick has been cast out, we can hope that the issues have been fixed upstream.

Can confirm, except on Void-Linux. I installed by maunaull unpacking and installing the .deb. The command works and all, but ortho can not use it. I think this may be related to the issues with the arch build as well. Maybe it is because of a Debian specific command or dependency. I am not sure.

**Comment by JT8D-17** [comment]
Had the same issue. Considering that NVidia Texture Tools is not being developed anymore, going back to Imagemagick may be the best long-term option.

This took me longer than I wanted because I'm really unfamiliar with Python, but I think I managed to get Imagemagick to work with DXT level support based on the patch above. Tile texture conversions at least don't fail with this and X-Plane doesn't crash.

In src/O4_Imagery_Utils.py:

Line 58: 
`dds_convert_cmd = "convert"`
Line 1426:
`conv_cmd=[dds_convert_cmd,'-format','dds','-define','dds:compression=dxt1',file_to_convert,os.path.join(tile.build_dir,'textures',out_file_name)]`
Line 1428:
`conv_cmd=[dds_convert_cmd,'-format','dds','-define','dds:compression=dxt5',file_to_convert,os.path.join(tile.build_dir,'textures',out_file_name)]`
