### ISSUE TITLE
Unable to use latest version of Python (macOS 14.5)

### ISSUE THREAD

**Issue by shred86** [oscarpilote/Ortho4XP#257]
I noticed in the 1.40 notes it mentions updates were made to work with "recent" versions of Python. However, I'm unable to get it to work with the latest version of Python 3.12.3. I can get it working using Python 3.10. I'm not sure if it's worth trying to fix Ortho4XP to work with the latest version of Python or to just instruct users to use Python 3.10.

If it's worth trying to fix Ortho4XP to work with Python 3.12.3, it looks like you have to also install the setuptools package since disutils was deprecated from Python in the newer versions. However, even after installing setuptools, I'm seeing this error when trying to run Ortho4XP:

`ModuleNotFoundError: No module named 'setuptools.extern.six'`

If it's easier from a maintenance perspective to just make Python 3.10 the requirement for Ortho4XP, then the macOS install instructions will need to be updated. I was able to get it to work based on [this thread](https://forums.x-plane.org/index.php?/forums/topic/302691-ortho4xp-140-on-macos-14sonoma/). Summary of the steps:

### Ortho4XP macOS installation instructions

Install Homebrew:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

Install the required Homebrew packages (of note, this will take a while 30-60 mins, if not longer):
`brew install python@3.10 python-tk@3.10 gdal spatialindex p7zip proj`

Install the required Python packages:
`pip3.10 install pyproj GDAL numpy Shapely==1.7.1 Rtree==0.9.7 pillow requests scikit-fmm`

Before running Ortho4XP, browse to Utils -> mac in the Ortho4XP folder using Finder and open DSFTool, nicompress, triangle, and Triangle4XP. When you open each application, macOS will not allow them to open so you'll have to go into your security settings and allow them to be opened/executed. You only have to do this once.

Then you can run Ortho4XP:
`python3.10 Ortho4XP.py`

### Notes

I noticed there are several Python packages in requirements.txt that I didn't install and it still seems to work, specifically `certifi`, `chardet`, and `urllib3`. Are these specific for Windows users because in install_mac.sh they aren't listed either.

Anyways, just trying to help clean up some of the instructions. As a new user to Ortho4XP on macOS, I found it very confusing trying to make sense of all the various information spread across different forum threads spanning over multiple years. I think updating the instructions here on this official repo would be the best solution to help users get setup.

**Comment by OldSubSailor** [comment]
Just a note, works fine with python3.11

**Comment by shred86** [comment]
When I followed the original instructions, it just uses `brew install python` so the latest version 3.12 ends up getting installed. You're saying if you install gdal, it will pull 3.11 specifically? Either way, relying on gdal's dependencies is probably not a great plan since that can change any time. Unless Ortho4XP is being updated to work with the latest dependencies, it's probably better to be explicit about the specific versions to install.

**Comment by OldSubSailor** [comment]
Well, I have _slept_ since and that may have happened in the old 1.30 days.  
I am still getting used to Sonoma (new Mac mini) and 1.40.  Things seem to have changed each time that I install Homebrew.
I noticed last week that Homebrew no longer installs things with the initial install that it used to.  

My apologies, my complete bad.  

To be honest now,  in looking at my April 3 version of Orth04XP 1.40, it  does include these instructions in the mac_install_sh file. 
_brew install gdal python@3.11 proj spatialindex p7zip python-tk@3.11_
I am not going the venv route by the way.  
[install_mac copy_sh.txt](https://github.com/oscarpilote/Ortho4XP/files/15504769/install_mac.copy_sh.txt)

**Comment by w8sl** [comment]
numpy==1.26.4
Pillow==10.3.0
pyproj==3.6.1
requests==2.31.0
Rtree==1.2.0
shapely==2.0.4
scikit-fmm
Are working fine with O4XP 1.40, Python 3.10 or 3.11.   GDAL dependencies are fixed by Homebrew. I am not aware of a possibility to change anything.
Using AutoOrtho + Ortho4XP on the same Mac is another thing, but it is possible to have 2 separate installations: one with python3.10 and pip3.10 (for AO) another with python3.11 and pip3.11(for O4XP). Costs about +100 mb on disk.
Install on Python 3.12 is only possible in venv, as global pip3 install has been disabled by Homebrew (for Python 3.12)

**Comment by OldSubSailor** [comment]
Good, the pro is here, and he will take good care of you.

**Comment by w8sl** [comment]
Getting rid of install_mac.sh is a good idea. Nobody seems to use it anyway, it usually gets outdated before merged and it generates security warnings on Sonoma. Besides, there may be important messages after brew install. As of today - no pinned versions are required. Charset-normalizer, urrlib, idna, certifi are installed automatically by pip.

**Comment by shred86** [comment]
Appreciate the info. I made a [pull request ](https://github.com/oscarpilote/Ortho4XP/pull/259)with updates to the installation instructions. I think adding these installation instructions to the main read me and using markdown to format it would be better, but that's really @oscarpilote call. More than happy to do the work as it's obviously pretty simple.

**Comment by shred86** [comment]
Closing since I created a new issue with a proposal on improving Ortho4XP. Also, I have incorporated most of ideas on my [forked version](https://github.com/shred86/Ortho4XP) for now.

**Comment by OldSubSailor** [comment]
OK, this is closed and all, however, how many versions do we need out there?

**Comment by shred86** [comment]
This repo isn't actively being maintained, so it's going to take a while to get any updates merged in. Instead of waiting months, if not years, I decided to just fork the repo to be able to provide updates that will hopefully make it back to this official version.

**Comment by OldSubSailor** [comment]
Well, there is that.
